---
# tasks file for playbooks/roles/harden

# This is remote!
- name: "Generate SSH key pair"
  openssh_keypair:
    path: '/tmp/id_adrestia'
    type: ed25519
    comment: "adrestia@{{ user.hostname }}"
  register: ssh_keys
  tags:
    - harden
    - ssh

- name: "Fetch generetad private SSH key"
  when: ssh_keys.changed
  fetch:
    flat: yes
    src: '/tmp/{{ item }}'
    dest: "{{ security.secrets + '/ssh/' }}"
  loop:
    - id_adrestia
    - id_adrestia.pub
  tags:
    - harden
    - ssh

- debug:
    var: ssh_keys
- debug:
    var: security
    

- name: "Upload generated SSH key as authorized_key"
  authorized_key:
    user: adrestia
    state: present
    key: "{{ ssh_keys.public_key }}"
  tags:
    - harden
    - ssh

#TODO (glost) ADD FINGERPRINT TO AUTHORIZED HOSTS!

- name: "Harden SSH via secure configuration"
  become: true
  template: 
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: yes
    owner: root
    group: root
    mode: 0600
    validate: '/usr/sbin/sshd -t -f %s'
  notify:
    - Restart SSH server
  tags:
    - harden
    - ssh
