---
# tasks file for playbooks/roles/harden

# Note(glost): This is remote! local_action: or delegate_to: 127.0.0.1 for host actions
- name: "Generate SSH key pair"
  openssh_keypair:
    path: '/tmp/id_adrestia'
    type: ed25519
    comment: "adrestia@{{ user.hostname }}"
  register: ssh_keys
  notify:
    - Fetch SSH keys
  tags:
    - ssh

- debug: 
    var: security

# TODO (glost) Delete generated keys from tmp location
    
- name: "Upload generated SSH key as authorized_key"
  authorized_key:
    user: adrestia
    state: present
    key: "{{ ssh_keys.public_key }}"
  tags:
    - ssh

#FIXME (glost) Does not work
- name: Make server known to host
  known_hosts:
    name: '{{ host }}'
    key: '{{ host }} {{ ssh_keys.public_key }}'
  vars:
    host: "[{{ ansible_host }}]:{{ security.ssh_port_number }}"

- name: "Harden SSH via secure configuration"
  become: true
  template: 
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: yes
    owner: root
    group: root
    mode: 0600
    validate: '/usr/sbin/sshd -t -f %s'
  notify:
    - Restart SSH server
  tags:
    - ssh

- name: Update/Install UFW
  become: true
  apt:
    name: ufw
    state: latest
    cache_valid_time: 3600

- name: Deny all access on default
  become: true
  ufw:
    state: enabled
    policy: deny

- name: Open ports for SSH and OpenVPN
  become: true
  ufw:
    port: '{{ item.port }}'
    proto: '{{ item.proto }}' 
    rule: allow 
    state: enabled 
  loop:
    - { port: '{{ security.ssh_port_number }}', proto: tcp }
    - { port: '{{ security.openvpn_port_number}}', proto: udp }
