---
# handlers file for playbooks/roles/harden
- name: Restart SSH server
  become: true
  service: name=sshd state=restarted
  tags: 
    - ssh

- name: "Fetch SSH keys"
  fetch:
    flat: yes
    src: '/tmp/{{ item }}'
    dest: "{{ security.secrets + '/ssh/' }}"
  loop:
    - id_adrestia
    - id_adrestia.pub
  tags:
    - ssh