all:
  hosts:
    adrestia_bootstrap: # password root login for first installation
      #ask for pw on bash
      ansible_host: 127.0.0.1 # User supplied
      ansible_port: 2222 # thanks VBOX
      ansible_user: adrestia # we ask user to create adrestia user (for now)
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    adrestia: # generated SSH login after hardening
        ansible_host: 127.0.0.1 # User supplied
        ansible_user: adrestia # we ask user to create adrestia user (for now)
        ansible_port: "{{ security.ssh_port_number }}"
        ansible_ssh_private_key_file: "{{ security.secrets }}/ssh/id_adrestia"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no' #FIXME (glost) until known_hosts fails