all:
  hosts:
    adrestia_bootstrap: # password root login for first installation
      #ask for pw on bash
      ansible_host: 127.0.0.1
      ansible_port: 2222 # thanks VBOX
      ansible_user: adrestia
    adrestia: # generated SSH login after hardening
        ansible_host: 127.0.0.1
        ansible_user: adrestia
        ansible_port: "{{ security.ssh_port_number }}"
        ansible_ssh_private_key_file: "{{ security.secrets }}/ssh/id_adrestia"