version: "3"
# NOTE (GLOST) ATTENTION!! THIS COMPOSE STILL USES STATIC IPS!!
services: 
  cron:
    image: alpine
    restart: always
    command: sh -c "echo \"0 3 * * * wget http://app/cron/run/{{ APPI_KEY MUST BE GOTTEN THROUGH THE INSTANCE }}\" | crontab - && crond -f -L /dev/stdout"
  app: 
    environment: 
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD={{ user.generated.fireflyiii_db_pass }}
      - APP_KEY={{ WHERE DID THE API KEY CAME FROM? }}
      - APP_ENV=local
      - DB_CONNECTION=pgsql
      - TZ=Europe/Amsterdam #TODO (glost) Var for that too
      - APP_LOG_LEVEL=debug
      - PGSQL_SSL_MODE=disable
      - CER_PROVIDER=ratesapi
      - LOGIN_PROVIDER=eloquent
    image: jc5x/firefly-iii
    restart: always
    networks: 
        default:
        vpn:
                ipv4_address: 172.20.20.10
    volumes: 
      - 
        source: export
        target: /var/www/firefly-iii/storage/export
        type: volume
      - 
        source: upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
  db: 
    environment: 
      - POSTGRES_PASSWORD={{ user.generated.fireflyiii_db_pass }}
      - POSTGRES_USER=firefly
    image: "postgres:10"
    restart: unless-stopped
    volumes: 
      - "db:/var/lib/postgresql/data"
networks: 
  vpn: 
    external:
        name: {{ user.main_network_name }}
volumes: 
  db: 
  export:
  upload:
