version: '3'
# NOTE (GLOST) ATTENTION!! THIS COMPOSE STILL USES STATIC IPS!!
services:
        onlyoffice:
                image: onlyoffice/documentserver
                stdin_open: true
                tty: true
                restart: unless-stopped
                expose:
                       - "80"
                       - "443"
                volumes:
                       - onlyoffice-data:/var/www/onlyoffice/Data
                       - onlyoffice-log:/var/log/
                networks:
                        vpn:
                                ipv4_address: 172.20.20.7
        db:
                image: mariadb
                restart: unless-stopped
                command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
                volumes:
                        - db:/var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD={{ user.generated.nextcloud_db_root_pass }}
                        - MYSQL_PASSWORD={{ user.generated.nextcloud_db_pass }}
                        - MYSQL_DATABASE=nextcloud
                        - MYSQL_USER=nextcloud

        redis:
                image: redis:alpine
                restart: unless-stopped

        app:
                build: ./app
                restart: unless-stopped
                volumes:
                        - app:/var/www/html
                environment: 
                        - REDIS_HOST=redis
                        - MYSQL_HOST=db
                        # TODO (GLOST): Actual create this var!
                        - MYSQL_PASSWORD= {{ user.generated.nextcloud_db_pass }}
                        - MYSQL_DATABASE=nextcloud
                        - MYSQL_USER=nextcloud
                        - NEXTCLOUD_TRUSTED_DOMAINS="172.20.20.3 app cloud.ichigo" # TODO (glost) Needs adjustment
                depends_on:
                        - db
                        - redis
                networks:
                        default:
                        vpn:
                                ipv4_address: 172.20.20.3

        cron:
                build: ./app
                restart: unless-stopped
                volumes:
                        - app:/var/www/html
                entrypoint: /cron.sh
                depends_on:
                        - db
                        - redis
volumes:
        db:
        app:
        onlyoffice-data:
        onlyoffice-log:

# TODO (Glost) Actual create the network + network var
networks:
        vpn:
                external:
                        name: {{ user.main_network_name }}

