version: "3"
# NOTE (GLOST) ATTENTION!! THIS COMPOSE STILL USES STATIC IPS!!
# TODO (glost): Auto config via Env vars
services:
  app:
    image: linuxserver/piwigo
    container_name: piwigo.{{ user.hostname }} # This should be in all containers
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin # TODO (glost) Var/Autodetect timezone
    volumes:
      - app:/config
    restart: unless-stopped
    networks:
      default:
      vpn:
        ipv4_address: 172.20.20.15

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD={{ user.generated.piwigo_db_root_pass }}
      - MYSQL_PASSWORD={{ user.generated.piwigo_db_pass }}
      - MYSQL_DATABASE=piwigo
      - MYSQL_USER=piwigo
    volumes:
      - db:/var/lib/mysql
networks:
  vpn:
    external:
      name: {{ user.main_network_name }}
volumes:
  app:
  db:
