---
# tasks file for playbooks/roles/piwigo
- name: Create service folder
  file:
    path: ~/docker/piwigo/
    state: directory

- name: Template out service compose file
  template:
      dest: ~/docker/piwigo/docker-compose.yml
      src: docker-compose.yml.j2 

- name: Start service via compose
  docker_compose:
    build: yes
    pull: yes
    project_src: ~/docker/piwigo
  register: output

- debug:
    var: output