---
- import_playbook: bootstrap-python.yml
  tags: 
    - bootstrap

- hosts: adrestia_bootstrap
  vars_files:
    - '{{ playbook_dir }}/../config/user.yml'
    - '{{ playbook_dir }}/../config/defaults.yml'
  tags:
    - bootstrap
  roles:
    - role: harden
      tags:
        - harden

- hosts: adrestia
  gather_facts: true
  tasks:
  - debug: 
      var:  ansible_private_key
  vars_files:
    - '{{ playbook_dir }}/../config/user.yml'
    - '{{ playbook_dir }}/../config/defaults.yml'
  #roles:
  #  - conn-check