---
- import_playbook: bootstrap-python.yml
  tags: 
    - bootstrap

- hosts: adrestia_bootstrap
  vars_files:
    - '{{ playbook_dir }}/../config/user.yml'
    - '{{ playbook_dir }}/../config/defaults.yml'
  tags:
    - bootstrap
  roles:
    - role: harden
      tags:
        - harden

- hosts: adrestia
  gather_facts: true
  tasks:
  vars_files:
    - '{{ playbook_dir }}/../config/user.yml'
    - '{{ playbook_dir }}/../config/defaults.yml'
  roles:
    - role: update
      become: true
      tags: update
    - role: docker-host
      become: true
      tags: docker-host